services:
  - type: web
    name: toobarter
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAILS
        sync: false
      - key: PAYMENT_INSTRUCTIONS
        sync: false
